const ACTIONS = {
	ADD_ITEM: "ADD_ITEM",
	LOAD_ITEMS: "LOAD_ITEMS",
	UPDATE_ITEM: "UPDATE_ITEM",
	DELETE_iTEM: "DELETE_iTEM",
	IS_LOADING: "IS_LOADING",
	OPEN_TOAST: "OPEN_TOAST",
	SEARCH: "SEARCH",
};

export default ACTIONS;
