const ACTIONS = {
    ADD_ITEMS : "ADD_ITEMS",
    UPDATE_EDIT_ICON : "UPDATE_EDIT_ICON",
    DELETE_ITEM : "DELETE_ITEM",
    EDIT_ITEM_NAME : "EDIT_ITEM_NAME",
    DISPLAY_LOADER: "DISPLAY_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    CHECKBOX_UPDATE : "CHECKBOX_UPDATE"
    
    

};

export default ACTIONS;