const ACTIONS = {
   
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    ADD_ITEMS: "ADD_ITEMS",
    DELETE_ITEM: "DELETE_ITEM",
    EDIT_ITEM_TO_NEW_NAME: "EDIT_ITEM_TO_NEW_NAME",
    UPDATE_CHECKBOX: "UPDATE_CHECKBOX",
    CLEAR_ALL_ITEMS: "CLEAR_ALL_ITEMS",
    UPDATE_SEARCH_INPUT: "UPDATE_SEARCH_INPUT",
    UPDATE_SELECT_INPUT: "UPDATE_SELECT_INPUT",
    
    

};

export default ACTIONS;