const ACTIONS = {
   
    ADD_ITEMS:"ADD_ITEMS",
    DELETE_ITEM:"DELETE_ITEM",
    CLEAR_ALL_ITEMS:"CLEAR_ALL_ITEMS",
    UPDATE_SEARCH_INPUT: "UPDATE_SEARCH_INPUT",
    UPDATE_SELECT_INPUT: "UPDATE_SELECT_INPUT",
    EDIT_ITEM_NAME:"EDIT_ITEM_NAME",
    DISPLAY_LOADER:"DISPLAY_LOADER",
    HIDE_LOADER:"HIDE_LOADER",
    CHECKBOX_UPDATE:"CHECKBOX_UPDATE"
    
    

};

export default ACTIONS;