const ACTIONS = {
   // Loader action types
   SHOW_LOADER: "SHOW_LOADER",
   HIDE_LOADER: "HIDE_LOADER",

   // API action types
   GET_TASKS: "GET_TASKS",
   SET_TASKS: "SET_TASKS",

   ADD_TASK: "ADD_TASK",
   ADD_TASK_FULFILLED: "ADD_TASK/fulfilled",
   ADD_TASK_REJECTED: "ADD_TASK/rejected",

   CLEAR_TASKS: "CLEAR_TASKS",
   CLEAR_TASKS_FULFILLED: "CLEAR_TASKS/fulfilled",
   CLEAR_TASKS_REJECTED: "CLEAR_TASKS/rejected",

   SORT_TASKS: "SORT_TASKS",
   SORT_TASKS_FULFILLED: "SORT_TASKS/fulfilled",
   SORT_TASKS_REJECTED: "SORT_TASKS/rejected",

   DELETE_TASK: "DELETE_TASK",
   DELETE_TASK_FULFILLED: "DELETE_TASK/fulfilled",
   DELETE_TASK_REJECTED: "DELETE_TASK/rejected",

   CHECKMARK_TASK: "CHECKMARK_TASK",
   CHECKMARK_TASK_FULFILLED: "CHECKMARK_TASK/fulfilled",
   CHECKMARK_TASK_REJECTED: "CHECKMARK_TASK/rejected",
};

export default ACTIONS;
