const ACTIONS = {
   // API action types
   GET_TASKS: "GET_TASKS",
   GET_TASKS_PENDING: "GET_TASKS/pending",
   GET_TASKS_FULFILLED: "GET_TASKS/fulfilled",
   GET_TASKS_REJECTED: "GET_TASKS/rejected",
   SET_TASKS: "SET_TASKS",

   ADD_TASK: "ADD_TASK",
   ADD_TASK_PENDING: "ADD_TASK/pending",
   ADD_TASK_FULFILLED: "ADD_TASK/fulfilled",
   ADD_TASK_REJECTED: "ADD_TASK/rejected",

   CLEAR_TASKS: "CLEAR_TASKS",
   CLEAR_TASKS_FULFILLED: "CLEAR_TASKS/fulfilled",
   CLEAR_TASKS_REJECTED: "CLEAR_TASKS/rejected",

   SORT_TASKS: "SORT_TASKS",
   SORT_TASKS_FULFILLED: "SORT_TASKS/fulfilled",
   SORT_TASKS_REJECTED: "SORT_TASKS/rejected",

   DELETE_TASK: "DELETE_TASK",
   DELETE_TASK_FULFILLED: "DELETE_TASK/fulfilled",
   DELETE_TASK_REJECTED: "DELETE_TASK/rejected",

   UNDO_DELETE: "UNDO_DELETE",
   UNDO_DELETE_FULFILLED: "UNDO_DELETE/fulfilled",
   UNDO_DELETE_REJECTED: "UNDO_DELETE/rejected",

   CHECKMARK_TASK: "CHECKMARK_TASK",
   CHECKMARK_TASK_FULFILLED: "CHECKMARK_TASK/fulfilled",
   CHECKMARK_TASK_REJECTED: "CHECKMARK_TASK/rejected",

   // Filter action types
   SET_SEARCH_INPUT: "SET_SEARCH_INPUT",
   SET_DROPDOWN_FILTER: "SET_DROPDOWN_FILTER",
};

export default ACTIONS;
