const ACTIONS = {
  GET_ALL_TASKS: "GET_ALL_TASKS",
  ADD_TASK: "ADD_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  DELETE_ALL: "DELETE_ALL",
  RESTORE_TASK: "RESTORE_TASK",
  SET_LOADER:"SET_LOADER",

  SET_SEARCH_INPUT:"SET_SEARCH_INPUT",
  SET_MARKED:"SET_MARKED",
};

export default ACTIONS;
