const ACTIONS = {
  FETCH: 'FETCH',
  ADD: 'ADD',
  DELETE: 'DELETE',
  CHECK: 'CHECK',
  EDIT_TEXT: 'EDIT_TEXT',
  SET_STATUS: 'SET_STATUS',
  DELETE_ALL: 'DELETE_ALL',
  SEARCH: 'SEARCH',
  SHOW_DONE: 'SHOW_DONE',
  SHOW_UNDONE: 'SHOW_UNDONE',
  SHOW_ALL: 'SHOW_ALL',
};

export default ACTIONS;
